export function getElectricFor24() {
  return {
    msg: "操作成功",
    code: 0,
    data: [
      {
        dataDate: "2014-06-23 00:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 01:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 02:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 03:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 04:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 05:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 06:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 07:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 08:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 09:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 10:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 11:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 12:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 13:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          cjMpId: 1,
          dataDate: "2014-06-23 13:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:26:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 14:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 5,
          cjMpId: 1,
          dataDate: "2014-06-23 14:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 15:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 9,
          cjMpId: 1,
          dataDate: "2014-06-23 15:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 15:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 16:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 13,
          cjMpId: 1,
          dataDate: "2014-06-23 16:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 16:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 17:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 17,
          cjMpId: 1,
          dataDate: "2014-06-23 17:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 17:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 18:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 21,
          cjMpId: 1,
          dataDate: "2014-06-23 18:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 18:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 19:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 25,
          cjMpId: 1,
          dataDate: "2014-06-23 19:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 19:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 20:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 29,
          cjMpId: 1,
          dataDate: "2014-06-23 20:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 20:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 21:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 22:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 23:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
    ],
  };
}

export function getElectricFor96() {
  return {
    msg: "操作成功",
    code: 0,
    data: [
      {
        dataDate: "2014-06-23 00:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 00:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 00:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 00:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 01:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 01:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 01:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 01:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 02:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 02:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 02:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 02:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 03:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 03:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 03:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 03:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 04:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 04:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 04:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 04:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 05:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 05:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 05:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 05:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 06:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 06:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 06:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 06:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 07:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 07:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 07:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 07:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 08:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 08:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 08:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 08:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 09:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 09:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 09:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 09:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 10:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 10:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 10:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 10:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 11:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 11:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 11:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 11:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 12:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 12:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 12:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 12:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 13:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 1,
          cjMpId: 1,
          dataDate: "2014-06-23 13:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:26:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 13:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 2,
          cjMpId: 1,
          dataDate: "2014-06-23 13:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 13:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 3,
          cjMpId: 1,
          dataDate: "2014-06-23 13:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 13:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 4,
          cjMpId: 1,
          dataDate: "2014-06-23 13:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 14:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 5,
          cjMpId: 1,
          dataDate: "2014-06-23 14:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 14:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 6,
          cjMpId: 1,
          dataDate: "2014-06-23 14:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:41:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 14:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 7,
          cjMpId: 1,
          dataDate: "2014-06-23 14:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:41:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 14:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 8,
          cjMpId: 1,
          dataDate: "2014-06-23 14:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 14:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 15:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 9,
          cjMpId: 1,
          dataDate: "2014-06-23 15:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 15:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 15:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 10,
          cjMpId: 1,
          dataDate: "2014-06-23 15:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 15:25:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 15:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 11,
          cjMpId: 1,
          dataDate: "2014-06-23 15:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 15:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 15:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 12,
          cjMpId: 1,
          dataDate: "2014-06-23 15:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 15:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 16:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 13,
          cjMpId: 1,
          dataDate: "2014-06-23 16:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 16:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 16:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 14,
          cjMpId: 1,
          dataDate: "2014-06-23 16:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 16:25:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 16:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 15,
          cjMpId: 1,
          dataDate: "2014-06-23 16:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 16:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 16:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 16,
          cjMpId: 1,
          dataDate: "2014-06-23 16:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 16:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 17:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 17,
          cjMpId: 1,
          dataDate: "2014-06-23 17:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 17:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 17:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 18,
          cjMpId: 1,
          dataDate: "2014-06-23 17:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 17:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 17:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 19,
          cjMpId: 1,
          dataDate: "2014-06-23 17:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 17:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 17:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 20,
          cjMpId: 1,
          dataDate: "2014-06-23 17:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 17:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 18:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 21,
          cjMpId: 1,
          dataDate: "2014-06-23 18:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 18:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 18:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 22,
          cjMpId: 1,
          dataDate: "2014-06-23 18:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 18:25:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 18:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 23,
          cjMpId: 1,
          dataDate: "2014-06-23 18:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 18:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 18:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 24,
          cjMpId: 1,
          dataDate: "2014-06-23 18:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 18:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 19:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 25,
          cjMpId: 1,
          dataDate: "2014-06-23 19:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 19:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 19:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 26,
          cjMpId: 1,
          dataDate: "2014-06-23 19:15:00",
          dataSource: "0",
          writeDate: "2014-06-23 19:25:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 19:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 27,
          cjMpId: 1,
          dataDate: "2014-06-23 19:30:00",
          dataSource: "0",
          writeDate: "2014-06-23 19:40:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 19:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 28,
          cjMpId: 1,
          dataDate: "2014-06-23 19:45:00",
          dataSource: "0",
          writeDate: "2014-06-23 19:55:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 20:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: 29,
          cjMpId: 1,
          dataDate: "2014-06-23 20:00:00",
          dataSource: "0",
          writeDate: "2014-06-23 20:10:00",
          zxygz: 0.59,
          fxygz: 0.43,
          zxwgz: 0.46,
          fxwgz: 0.4,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 20:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 20:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 20:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 21:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 21:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 21:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 21:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 22:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 22:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 22:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 22:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 23:00:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 23:15:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 23:30:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
      {
        dataDate: "2014-06-23 23:45:00",
        data: {
          createBy: null,
          createTime: null,
          updateBy: null,
          updateTime: null,
          remark: null,
          id: null,
          cjMpId: null,
          dataDate: null,
          dataSource: null,
          writeDate: null,
          zxygz: null,
          fxygz: null,
          zxwgz: null,
          fxwgz: null,
          field01: null,
          field03: null,
          field02: null,
        },
      },
    ],
  };
}
